"use client";

import { SpotlightCard } from "@ansospace/ui/blocks";
import { cn } from "@ansospace/ui/lib/utils";
import { formatDistanceToNow } from "date-fns";
import { History, Key, LogIn, ShieldCheck, UserCog } from "lucide-react";

const logs = [
  {
    id: 1,
    type: "security",
    action: "Password updated",
    createdAt: "2026-01-03T00:22:19Z",
    icon: Key,
    color: "text-amber-500",
  },
  {
    id: 2,
    type: "login",
    action: "Login from New Device",
    createdAt: "2026-01-02T21:22:19Z",
    icon: LogIn,
    color: "text-indigo-500",
  },
  {
    id: 3,
    type: "profile",
    action: "Avatar generated by AI",
    createdAt: "2026-01-02T02:22:19Z",
    icon: UserCog,
    color: "text-purple-500",
  },
  {
    id: 4,
    type: "security",
    action: "2FA state synchronized",
    createdAt: "2026-01-01T02:22:19Z",
    icon: ShieldCheck,
    color: "text-emerald-500",
  },
];

export function ActivityLog() {
  return (
    <SpotlightCard className="flex h-full flex-col p-6">
      <div className="mb-6 flex items-center gap-2">
        <div className="rounded-lg border border-indigo-500/20 bg-indigo-500/10 p-2">
          <History className="size-5 text-indigo-500" />
        </div>
        <h3 className="font-bold tracking-tight">Recent Activity</h3>
      </div>

      <div className="space-y-4">
        {logs.map((log) => (
          <div key={log.id} className="group relative flex items-start gap-3">
            <div className={cn("mt-1 rounded-full p-1", log.color, "bg-current/10")}>
              <log.icon className="size-3.5" />
            </div>
            <div className="border-border/40 flex flex-1 flex-col border-b border-dashed pb-3 transition-colors group-last:border-0">
              <span className="text-xs font-semibold">{log.action}</span>
              <span className="text-muted-foreground text-[10px]">
                {formatDistanceToNow(new Date(log.createdAt), { addSuffix: true })}
              </span>
            </div>
          </div>
        ))}
      </div>

      <button className="text-muted-foreground hover:text-primary mt-auto w-full pt-6 text-center text-[10px] font-bold tracking-widest uppercase transition-colors">
        View Full Audit Log
      </button>
    </SpotlightCard>
  );
}
